//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public int CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public int AddressTypeId { get; set; }
        public string ApplicationUserId { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual City City { get; set; }
        public virtual State State { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
