//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public int Id { get; set; }
        public Nullable<int> CarMaker { get; set; }
    
        public virtual CarMake CarMake { get; set; }
    }
}
