//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoreUserDetail
    {
        public int id { get; set; }
        public string HomeStreetAddress { get; set; }
        public string HomeCityName { get; set; }
        public string HomeLivingStateName { get; set; }
        public string WorkStreetAddress { get; set; }
        public string WorkCityName { get; set; }
        public string WorkStateName { get; set; }
        public string user_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
