//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaRequest
    {
        public int refid { get; set; }
        public string SocialMedia { get; set; }
        public string FriendName { get; set; }
        public string FriendsEmail { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TripId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
