//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripNetwork
    {
        public int Id { get; set; }
        public Nullable<int> TripsId { get; set; }
        public string TripMembers { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<bool> AcceptedOrRejectedByAdmin { get; set; }
        public Nullable<System.DateTime> DateTripAdminAcceptedOrRejected { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
