//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.TripNetworks = new HashSet<TripNetwork>();
            this.SocialMediaRequests = new HashSet<SocialMediaRequest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StartLocationId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public string TripAdmin { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Charge { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripNetwork> TripNetworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMediaRequest> SocialMediaRequests { get; set; }
    }
}
