//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowMyneighbour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRoute
    {
        public int id { get; set; }
        public string StartLocation { get; set; }
        public string DestinationLocation { get; set; }
        public string userid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
